### ISSUE TITLE
Incorrect typing?

### ISSUE THREAD

**Issue by willpower232** [beyondcode/slack-notification-channel#15]
I am using this library for the sole purpose of easy slack thread replies as per the example in the readme.

I wrote a whole bunch of code which worked flawlessly and then phpstan pointed out that `threadTimestamp` expected a native date related class or an int

https://github.com/beyondcode/slack-notification-channel/blob/7cd48f69f8852eabfc3464b0ebc15d632bdecd55/src/Messages/SlackMessage.php#L292

I cast the `ts` value to an int and my code immediately stopped working. I also tried a quick convert to `\Datetime` and this also did not work.

In both of these situations, Slack still posts the message but it does not thread as intended. As far as I can tell, this method only works with string.

Am I going mad?

**Comment by willpower232** [comment]
aha this value can never be an int

![image](https://github.com/beyondcode/slack-notification-channel/assets/1619102/f684823f-bf95-4ad4-bed9-b6be513ba5fd)

**Comment by mpociot** [comment]
Thanks, fixed it 👍

**Comment by willpower232** [comment]
Much obliged! I look forward to the next release :pray:
